<span class="floating-images wha-yellow-dots">
    <img class="img-fluid" src="assets/images/yellow-dots.png" alt="what-bg-yellow-dots" />
</span>
<span class="floating-images wha-bg-left">
    <img class="img-fluid" src="assets/images/MFS_BG.png" alt="what-is-it-bg" />
</span>
<span class="floating-images wha-bg-right">
    <img class="img-fluid" src="assets/images/MFS_BG.png" alt="MFS_BG" />
</span>
<span class="floating-images wha-pink-line">
    <img class="img-fluid" src="assets/images/pink-line.png" alt="bg" />
</span>

<span class="floating-images why-green-line">
    <img class="img-fluid" src="assets/images/green-line.png" alt="why-bg-greenline" />
</span>
<span class="floating-images why-bg-img">
    <img class="img-fluid" src="assets/images/why-create-bg.png" alt="why-create-bg" />
</span>
<span class="floating-images why-yellow-dots">
    <img class="img-fluid" src="assets/images/yellow-dots.png" alt="why-create-bg-yellow-dots" />
</span>
<span class="floating-images why-bg-right">
    <img class="img-fluid" src="assets/images/why-create-bg-right.png" alt="why-create-bg-right" />
</span>

<span class="floating-images att-pink-dots">
    <img class="img-fluid" src="assets/images/pink-dots.png" alt="attend-pink-dots" />
</span>
<span class="floating-images att-green-line">
    <img class="img-fluid" src="assets/images/green-line.png" alt="attend-green-line" />
</span>
<span class="floating-images att-pink-line">
    <img class="img-fluid" src="assets/images/pink-line.png" alt="attend-pink-line" />
</span>
<span class="floating-images att-yellow-line">
    <img class="img-fluid" src="assets/images/yellow-line.png" alt="attend-yellow-line" />
</span>

<span class="floating-images last-show-bg-left">
    <img class="img-fluid" src="assets/images/last-show-bg.png" alt="last-show-bg-left" />
</span>            
<span class="floating-images last-show-green-dots">
    <img class="img-fluid" src="assets/images/green-dots.png" alt="last-show-green-dots" />
</span>