<div class="banner">
    <div class="container">
        <div class="bannerIn">
            <div class="banner-txt">
                <div class="txt-In">
                    <h4 class="color-green">THE UK’S</h4>
                    <h2 class="color-pink">LEADING</h2>
                    <h3 class="color-green">FAMILY BUILDING</h3>
                    <h4 class="color-pink">EVENT IS BACK</h4>
                    <h3 class="color-white date-txt">23.9.23</h3>
                    <h6 class="color-white location-txt">8 Northumberland, London</h6>
                </div>
            </div>
            <div class="banner-btn">
                <a href="#" class="btn btn-book">BOOK TICKETS <span>NOW</span></a>
            </div>  
            <div class="banner-image">
                <img src="assets/images/banner-peoples-group.png" alt=""/>
            </div>          
        </div>
    </div>
    <div class="banner-overlay-white-bt"></div>
    <div class="banner-overlay-green-bt"></div>
    <div class="banner-overlay-pink-rt"></div>
    <div class="banner-overlay-green-lt"></div>
</div>