<div data-wow-delay="0.8s" class="wow fadeInUp banner">
    <div class="container">
        <div data-wow-delay="0.9s" class="wow fadeInUp bannerIn">
            <div data-wow-delay="1s" class="wow fadeInUp banner-txt">
                <div data-wow-delay="1.2s" class="wow fadeInUp txt-In">
                    <h4 class="color-green">THE UK’S</h4>
                    <h2 class="color-pink">LEADING</h2>
                    <h3 class="color-green">FAMILY BUILDING</h3>
                    <h4 class="color-pink">EVENT IS BACK</h4>
                    <h3 class="color-white date-txt">23.9.23</h3>
                    <h6 class="color-white location-txt">8 Northumberland, London</h6>
                </div>
            </div>
            <div data-wow-delay="1.2s" class="wow fadeInUp hexa-btn">
                <a href="https://www.eventbrite.co.uk/e/444620099687" target="_blank" class="btn btn-book">BOOK TICKETS <span>NOW</span></a>
            </div>  
            <div data-wow-delay="1.3s" class="wow fadeInUp banner-image">
                <img src="assets/images/banner-peoples-group.png" alt=""/>
            </div>          
        </div>
    </div>
    <div data-wow-delay="1.4s" class="wow fadeInUp banner-overlay-white-bt"></div>
    <div data-wow-delay="1.5s" class="wow fadeInUp banner-overlay-green-bt"></div>
    <div data-wow-delay="1.6s" class="wow fadeInUp banner-overlay-pink-rt"></div>
    <div data-wow-delay="1.7s" class="wow fadeInUp banner-overlay-green-lt"></div>
</div>