<!-- START : FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h5 class="text-uppercase">Email</h5>

                <p class="MFS_footer_link">
                    <a href="mailto:hello@themodernfamilyshow.com">hello@themodernfamilyshow.com</a>
                </p>
                <div class="subscribe-btn-container">
                    <a class="subscribe_now_btn popup-modal" href="#subscribe-modal">SUBSCRIBE NOW</a>
                </div>
                <ul class="social-icon-list">
                    <li><a href="https://www.facebook.com/TheModernFamilyShow/"><i class="fa-brands fa-facebook"></i></a></li>
                    <li><a href="https://www.instagram.com/themodernfamilyshow"><i class="fa-brands fa-instagram"></i></a></li>
                    <li><a href="https://twitter.com/TheModernFamil1"><i class="fa-brands fa-twitter"></i></a></li>
                    <li><a href="https://www.linkedin.com/company/64725406"><i class="fa-brands fa-linkedin"></i></a></li>
                </ul>
            </div>

            <div class="col-lg-3">
                <h5 class="text-uppercase">Links</h5>
                <ul class="footer_links">
                    <li><a href="index.shtml">Home</a></li>
                    <li><a href="about.shtml">About</a></li>
                    <li><a href="blog.shtml">Blog</a></li>
                    <li><a href="contact.shtml">Contact Us</a></li>
                    <li><a href="images/mfs-events-ltd-data-privacy-policy.pdf">Privacy Policy</a></li>
                </ul>
            </div>

            <div class="col-lg-3">
                <!--<h5 class="text-uppercase">Past Events</h5>
                <ul>
                    <li><a href="#">London 22</a></li>
                </ul>-->
            </div>

            <div class="col-lg-3">
                <h5 class="text-uppercase">Contact Us</h5>
                <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
                <script>
                hbspt.forms.create({
                    region: "eu1",
                    portalId: "25374820",
                    formId: "98fcfe80-a497-42e9-a83f-07f373fd307b"
                });
                </script>


                <!--<form class="contact_form" id="contact_form">
                    <input type="text" class="form-control" placeholder="YOUR NAME">
                    <input type="email" class="form-control" placeholder="YOUR EMAIL">
                    <textarea class="form-control" id="contact_message" name="contact_message"></textarea>
                    <input type="submit" value="Submit" class="submit_btn" />
                </form> -->
            </div>
        </div>
    </div>
</div>

<div id="subscribe-modal" class="mfp-hide white-popup-block popup-wrap xs">
    <div class="image-content"><img src="assets/images/subscribe-form-image.jpg" alt="Subscribe Form" /></div>
    <div class="popIn">
        <h2>Register your interest and be a part of it!</h2>
        <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
        <script>
        hbspt.forms.create({
            region: "eu1",
            portalId: "25374820",
            formId: "10d3902e-5b6f-4a22-8be5-dad3676aa93b"
        });
        </script>
    </div>
</div>
<!-- END : FOOTER -->
    
<script src="assets/js/jquery-3.6.4.slim.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/jquery.magnific-popup.min.js"></script>
<script src="assets/js/main.js"></script>