<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="assets/css/bootstrap.min.css" rel="stylesheet"/>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="https://www.dafontfree.net/embed/Y2hhbnRpbGx5LXNlcmlhbC1oZWF2eS1yZWd1bGFyJmRhdGEvMzYvYy8xMjY2NTcvY2hhbnRpbGx5LXNlcmlhbC1oZWF2eS1yZWd1bGFyLnR0Zg" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="assets/css/style.css">

<link rel="stylesheet" href="assets/css/media.css">