<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="facebook-domain-verification" content="48qsvlrtn3zxrqsrbr1vwtias8o8ew" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700;900&display=swap" rel="stylesheet">
<link href="assets/css/bootstrap.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"/>
<link href="https://www.dafontfree.net/embed/Y2hhbnRpbGx5LXNlcmlhbC1oZWF2eS1yZWd1bGFyJmRhdGEvMzYvYy8xMjY2NTcvY2hhbnRpbGx5LXNlcmlhbC1oZWF2eS1yZWd1bGFyLnR0Zg" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="assets/css/owl.carousel.min.css">
<link rel="stylesheet" href="assets/css/magnific-popup.css">
<link rel="stylesheet" href="assets/css/style.css">
<link rel="stylesheet" href="assets/css/media.css">

<meta name="google-site-verification" content="oYyvKdD1MLtNGrwk3J93oIDNo7D9HL4VpRtApbuhjOY" />

	<!-- Global site tag (gtag.js) - Google Analytics -->

	<script async src="https://www.googletagmanager.com/gtag/js?id=G-7ERJZ0LP3V"></script>

	<script>

	  window.dataLayer = window.dataLayer || [];

	  function gtag(){dataLayer.push(arguments);}

	  gtag('js', new Date());





	  gtag('config', 'G-7ERJZ0LP3V');

	</script>

	<!-- Global site tag (gtag.js) - Google Ads: 10825368312 --> 

	<script async src="https://www.googletagmanager.com/gtag/js?id=AW-10825368312"></script> 

	<script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-10825368312'); </script>


    <!-- Meta Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '352756289522483');
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=352756289522483&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Meta Pixel Code -->