<!-- START : Header -->
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-2">
                    <a href="index.shtml"><img class="img-fluid logo" src="assets/images/logo.svg" alt="logo"></a>
                </div>

                <div class="col-lg-9 col-md-10">
                    <div class="menu justify-content-end">
                        <ul class="social-nav">
                            <li><a class="social-icon nav-link" href="https://www.facebook.com/TheModernFamilyShow/"><i class="fa-brands fa-facebook"></i></a></li>
                            <li><a class="social-icon nav-link" href="https://www.instagram.com/themodernfamilyshow"><i class="fa-brands fa-instagram"></i></a></li>
                            <li><a class="social-icon nav-link" href="https://twitter.com/TheModernFamil1"><i class="fa-brands fa-twitter"></i></a></li>
                            <li><a class="social-icon nav-link" href="https://www.linkedin.com/company/64725406"><i class="fa-brands fa-linkedin"></i></a></a></li>
                        </ul>
                        <ul>
                            <li class="nav-item"><a class="nav-link" href="index.shtml">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="about.shtml">About Us</a></li>
                            <li class="nav-item"><a class="nav-link" href="london23.shtml">London '23</a></li>
                            <li class="nav-item"><a class="nav-link" href="blog.shtml">Blog</a></li>
                            <li class="nav-item"><a class="nav-link" href="contact.shtml">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END : Header -->